'use strict';
// Real codec/adapter with synthetic accounts, no production or network saves.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const root={crypto:webcrypto,TextEncoder};root.globalThis=root;
for(const name of ['little_leaf_vault','little_leaf_firebase'])vm.runInNewContext(fs.readFileSync(`web/${name}.js`,'utf8'),root);
const codec=root.LittleLeafAuthorityCodec,api=root.LittleLeafFirebase,payload=fs.readFileSync('tests/fixtures/startup-retry-v15.json','utf8');
const deviceByDigest=new Map();
const clone=x=>x==null?null:JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),fail=code=>Object.assign(Error(code),{code});
async function record(revision,coins,profileId,device){const r={format:2,profileId,revision,createdAt:1,updatedAt:100+revision,payload:JSON.stringify({...JSON.parse(payload),coins}),digest:null,origin:{source:'fresh',legacyDigest:null,importedAt:1},previous:null,campaigns:{}};r.digest=await codec.hash(codec.fingerprint(r));if(device)deviceByDigest.set(r.digest,device);return r;}
const doc=r=>({schema:1,profileId:r.profileId,revision:r.revision,digest:r.digest,record:JSON.stringify(r),device:deviceByDigest.get(r.digest)||'Unknown device'});
async function harness({normal=false}={}){
 const profile=webcrypto.randomUUID(),base=await record(1,500,profile),localRecord=await record(2,100,profile),cloudRecord=normal?base:await record(3,900,profile,'iPhone');
 const original={base:base.digest,pending:true,record:localRecord,uploading:{base:base.digest,record:localRecord}};
 let uid='choice-user',local=clone(original),backup=null,cloud=doc(cloudRecord),writes=0,writeHook=null,chooseHook=null,readHook=null;
 const journal={async read(){return clone(local);},async replace(id,old,next){if(!same(local,old))throw fail('REVISION_CONFLICT');local=clone(next);},async readRecoveryBackup(){return null;},async recover(){throw Error('legacy API unused');},async readChoiceBackup(){return clone(backup);},async choose(id,expected,next,bundle,guard){if(chooseHook)await chooseHook();guard();if(backup&&!same(backup,bundle))throw fail('RECOVERY_ARCHIVE_FULL');if(same(local,next)&&same(backup,bundle))return;if(!same(local,expected))throw fail('REVISION_CONFLICT');backup=clone(bundle);local=clone(next);}};
 const remote={async read(){if(readHook)await readHook();return clone(cloud);},async compareAndSet(id,base,next,guard){guard();if(writeHook)await writeHook('before');if(cloud?.digest!==next.digest){if((cloud?.digest||null)!==base)throw fail('REVISION_CONFLICT');cloud=clone(next);writes++;}if(writeHook)await writeHook('after');}};
 const make=()=>api.createClient({uid:'choice-user',codec,journal,remote,currentUid:()=>uid,status(){},now:()=>1000,deviceLabel:'Mac'});
 return {c:make(),make,original,cloudRecord,base,journal,remote,local:()=>clone(local),backup:()=>clone(backup),cloud:()=>clone(cloud),writes:()=>writes,setCloud:x=>cloud=x,setLocal:x=>local=x,setBackup:x=>backup=x,setUid:x=>uid=x,onWrite:x=>writeHook=x,onChoose:x=>chooseHook=x,onRead:x=>readHook=x};
}
async function prepare(h,choice){const s=h.c.recoverySnapshot();return h.c.prepareChoice(choice,s.expectedLocalDigest,s.expectedCloudDigest);}
(async()=>{
 let h=await harness();assert.equal((await h.c.boot()).code,'REVISION_CONFLICT');let s=h.c.recoverySnapshot();assert(s.choicesAvailable);assert.deepEqual(clone(s.choices),[{id:'local',coins:100,lastSavedAt:102,timeSource:'device-local-save',device:'Unknown device'},{id:'cloud',coins:900,lastSavedAt:103,timeSource:'device-local-save',device:'iPhone'}]);assert.equal(h.writes(),0);assert.deepEqual(h.local(),h.original);
 let p=await prepare(h,'cloud');assert(p.ok);assert.deepEqual(h.local(),h.original);assert.equal(h.backup(),null);let r=await h.c.confirmChoice(p.selectionToken);assert(r.ok);assert.equal(r.payload,p.payload);assert.equal(r.revision,p.revision);assert.equal(h.writes(),0);assert.deepEqual(h.backup().local,h.original);assert.deepEqual(h.backup().cloud,h.cloudRecord);assert.equal(h.backup().cloudDocument.record,JSON.stringify(h.cloudRecord));assert((await h.c.confirmChoice(p.selectionToken)).ok);
 assert((await h.c.commit(payload,r.revision,r.profileId)).ok);assert.equal((await h.c.confirmChoice(p.selectionToken)).code,'RECOVERY_CHANGED');
 h=await harness();await h.c.boot();p=await prepare(h,'local');assert(p.ok);assert.equal(p.revision,4);assert.equal(JSON.parse(p.payload).coins,100,'explicit lower-coins branch retained');assert.equal(h.writes(),0);r=await h.c.confirmChoice(p.selectionToken);assert(r.ok);assert.equal(r.payload,p.payload);assert.equal(r.revision,p.revision);assert.equal(h.writes(),1);assert.equal(h.local().pending,false);assert.equal(h.local().device,'Mac');assert.equal(h.local().record.updatedAt,1000);assert.deepEqual(h.backup().local,h.original);assert.deepEqual(h.backup().cloud,h.cloudRecord);assert.equal(h.backup().cloudDocument.record,JSON.stringify(h.cloudRecord));assert((await h.c.confirmChoice(p.selectionToken)).ok);assert.equal(h.writes(),1);
 h=await harness();h.setLocal({...h.original,record:await record(2,55,webcrypto.randomUUID()),uploading:null});await h.c.boot();p=await prepare(h,'local');assert(p.ok);assert.equal(p.profileId,h.cloudRecord.profileId);assert((await h.c.confirmChoice(p.selectionToken)).ok);
 h=await harness();await h.c.boot();assert.equal((await h.c.confirmChoice('invented')).code,'RECOVERY_CONFIRMATION_REQUIRED');assert.equal((await h.c.prepareChoice('newest',h.original.record.digest,h.cloudRecord.digest)).code,'INVALID_CHOICE');
 for(const kind of ['cloud','local','account']){h=await harness();await h.c.boot();p=await prepare(h,'local');if(kind==='cloud')h.setCloud(doc(await record(5,1,h.cloudRecord.profileId)));if(kind==='local')h.setLocal({...h.original,record:await record(6,2,h.cloudRecord.profileId)});if(kind==='account')h.setUid('other');const before=h.local(),cloud=h.cloud();assert(!(await h.c.confirmChoice(p.selectionToken)).ok);assert.deepEqual(h.local(),before);assert.deepEqual(h.cloud(),cloud);assert.equal(h.backup(),null);}
 h=await harness();await h.c.boot();p=await prepare(h,'cloud');h.onChoose(()=>{throw fail('STORAGE_ERROR');});assert.equal((await h.c.confirmChoice(p.selectionToken)).code,'STORAGE_ERROR');assert.deepEqual(h.local(),h.original);assert.equal(h.backup(),null);h.onChoose(null);assert((await h.c.confirmChoice(p.selectionToken)).ok);
 h=await harness();await h.c.boot();p=await prepare(h,'local');h.onWrite(phase=>{if(phase==='after')throw fail('OFFLINE');});assert.equal((await h.c.confirmChoice(p.selectionToken)).code,'OFFLINE');assert.equal(h.writes(),1);assert(h.local().pending);assert.deepEqual(h.backup().local,h.original);h.onWrite(null);assert((await h.c.confirmChoice(p.selectionToken)).ok);assert.equal(h.writes(),1);
 h=await harness();await h.c.boot();p=await prepare(h,'local');h.onWrite(phase=>{if(phase==='after')throw fail('OFFLINE');});await h.c.confirmChoice(p.selectionToken);h.onWrite(null);r=await h.make().boot();assert(r.ok);assert.equal(r.payload,p.payload);assert.equal(h.writes(),1);assert(h.backup());
 h=await harness();await h.c.boot();p=await prepare(h,'local');const newer=doc(await record(8,800,h.cloudRecord.profileId));h.onWrite(phase=>{if(phase==='before')h.setCloud(newer);});assert.equal((await h.c.confirmChoice(p.selectionToken)).code,'REVISION_CONFLICT');assert.deepEqual(h.cloud(),newer);assert.equal(h.local().record.payload,p.payload);assert.deepEqual(h.backup().local,h.original);
 for(const backup of [{damaged:true},h.backup()]){const other=await harness();other.setBackup(backup);await other.c.boot();assert.equal(other.c.recoverySnapshot().choicesAvailable,false);assert(!(await prepare(other,'cloud')).ok);assert.deepEqual(other.backup(),backup);assert.deepEqual(other.local(),other.original);}
 h=await harness({normal:true});r=await h.c.boot();assert(r.ok);h.setCloud(doc(await record(10,1000,r.profileId)));await h.c.commit(payload,r.revision,r.profileId);const native=JSON.stringify({...JSON.parse(payload),coins:432});r=await h.c.preserveRuntime(native,3,r.profileId);assert(r.ok&&r.durable);assert.equal(r.revision,4);assert.equal(h.local().record.payload,native);assert(h.c.recoverySnapshot().choicesAvailable);h.setUid('other');const before=h.local();assert.equal((await h.c.preserveRuntime(payload,4,r.profileId)).code,'NOT_READY');assert.deepEqual(h.local(),before);
 // A network failure after protected selection supports the same card again.
 h=await harness();await h.c.boot();const preview=h.c.recoverySnapshot();p=await prepare(h,'local');h.onWrite(()=>{throw fail('OFFLINE');});assert.equal((await h.c.confirmChoice(p.selectionToken)).code,'OFFLINE');const retry=await h.c.prepareChoice('local',preview.expectedLocalDigest,preview.expectedCloudDigest);assert(retry.ok);assert.equal(retry.selectionToken,p.selectionToken);assert.equal(retry.payload,p.payload);h.onWrite(null);assert((await h.c.confirmChoice(retry.selectionToken)).ok);
 h=await harness({normal:true});h.onWrite(async phase=>{if(phase==='before')h.setCloud(doc(await record(8,888,h.cloudRecord.profileId)));});assert.equal((await h.c.boot()).code,'REVISION_CONFLICT');assert(h.c.recoverySnapshot().choicesAvailable,'cloud race during startup upload gets a choice preview');
 // The exact old fingerprint definition verifies new records; metadata is outside it.
 h=await harness();await h.c.boot();p=await prepare(h,'local');await h.c.confirmChoice(p.selectionToken);const committed=h.local().record;
 const legacy={format:committed.format,profileId:committed.profileId,revision:committed.revision,createdAt:committed.createdAt,updatedAt:committed.updatedAt,origin:committed.origin,payload:committed.payload};if(committed.format===2)legacy.campaigns=committed.campaigns;
 assert.equal(await codec.hash(JSON.stringify(legacy)),committed.digest);assert(!Object.hasOwn(committed,'saveDevice'));assert.equal(h.cloud().device,'Mac');
 // Explicit requested regression: stale cache with no new pending edits is not a conflict and never uploads.
 h=await harness();h.setLocal({record:h.base,base:h.base.digest,pending:false});r=await h.c.boot();assert(r.ok);assert.equal(r.payload,h.cloudRecord.payload);assert.equal(h.writes(),0);assert.equal(h.c.recoverySnapshot().choicesAvailable,false);
 assert.equal(api.genericDevice({userAgent:'Mozilla iPhone',platform:'iPhone'}),'iPhone');assert.equal(api.genericDevice({userAgent:'Mozilla',platform:'MacIntel',maxTouchPoints:5}),'iPad');assert.equal(api.genericDevice({userAgent:'secret-user-agent'}),'Unknown device');const metadata=await record(1,10,webcrypto.randomUUID(),'Mac');const envelope=doc(metadata);envelope.device='not-a-real-device';await codec.verifyRecord(JSON.parse(envelope.record));h=await harness();h.setCloud({...doc(h.cloudRecord),device:'invented secret platform'});await h.c.boot();assert.equal(h.c.recoverySnapshot().choices[1].device,'Unknown device');
 console.log('Save choice adapter: preparation, exact protected branches, explicit lower-coins choice, stale/account/storage/CAS races, lost acknowledgment/reload, full archive, native snapshot, harmless old-cache and coarse metadata passed.');
})().catch(e=>{console.error(e);process.exit(1);});
