'use strict';
const cp=require('node:child_process'),spawn=cp.spawn;cp.spawn=(command,args,options)=>spawn(command,args,{...options,windowsHide:true});
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const repo=path.resolve(__dirname,'../..'),out=path.resolve(process.env.BINDING_WEB_OUTPUT),web=path.join(out,'web');
const evidence=path.join(out,'browser-'+Date.now());fs.mkdirSync(evidence);
const scripts=['little_leaf_firebase.js','little_leaf_firebase_session.js','little_leaf_update.js','little_leaf_google_binding.js','little_leaf_google_binding_ui.js','little_leaf_local_google_entry.js'];
const setup=`
const clone=x=>x==null?null:JSON.parse(JSON.stringify(x));
const read=k=>JSON.parse(localStorage.getItem('synthetic-binding:'+k)||'null'),write=(k,v)=>localStorage.setItem('synthetic-binding:'+k,JSON.stringify(v));
const auth={currentUser:read('signedIn')?{uid:'synthetic-google',isAnonymous:false}:null,async authStateReady(){}};
window.__bindingTrace=[];const bindingCreate=LittleLeafGoogleBinding.create;
window.LittleLeafGoogleBinding={...LittleLeafGoogleBinding,create:options=>{const source=options.source;options={...options,source:async()=>{try{return await source();}catch(error){window.__bindingTrace.push({action:'read complete local source',error:error.message});throw error;}}};const binding=bindingCreate(options);return {...binding,inspect:async()=>{const result=await binding.inspect();window.__bindingTrace.push({action:'inspect',result});return result;}};}};
let listeners=[];
window.LittleLeafFirebaseSession={...window.LittleLeafFirebaseSession,createRemote:(db,sdk,uid)=>({async read(){return read('session');},async change(transition,guard){guard();const old=read('session'),next=transition(old,read('cloud'),()=>Date.now());guard();write('session',next);for(const listener of listeners)queueMicrotask(()=>listener(clone(next)));return clone(next);},watch(fn){listeners.push(fn);return()=>listeners=listeners.filter(x=>x!==fn);},async readCertificate(){return null;}})};
window.LittleLeafFirebase={...window.LittleLeafFirebase,createRemote:(db,sdk,ownership)=>({async read(){return read('cloud');},async compareAndSet(uid,base,next,guard){guard();const cloud=read('cloud');if(cloud?.digest===next.digest)return;if((cloud?.digest||null)!==base)throw Error('cloud changed');const owner=read('session');write('cloud',{...next,writerId:owner.owner,writerEpoch:owner.epoch,savedAt:Date.now()});write('writes',(read('writes')||0)+1);if(read('interrupt')){write('interrupt',false);location.reload();await new Promise(()=>{});}}})};
const initializeApp=()=>({}),getAuth=()=>auth,getFirestore=()=>({}),setPersistence=async()=>{},browserLocalPersistence={},GoogleAuthProvider=class{},getRedirectResult=async()=>null;
const signInWithPopup=async()=>{auth.currentUser={uid:'synthetic-google',isAnonymous:false};write('signedIn',true);return {user:auth.currentUser,providerId:'google.com'};},signInWithRedirect=signInWithPopup,getIdTokenResult=async()=>({claims:{firebase:{sign_in_provider:'google.com'}}}),signOut=async()=>{auth.currentUser=null;write('signedIn',false);},onAuthStateChanged=()=>()=>{};
const doc=()=>{},getDocFromServer=()=>{},runTransaction=()=>{},serverTimestamp=()=>Date.now(),onSnapshot=()=>{};
window.__bindingQA={read,write,async seedCloud(){const local=await LittleLeafLocalGoogleEntry.readLocalRecord(),cloud=clone(local);cloud.profileId=crypto.randomUUID();cloud.revision=9;cloud.previous=null;cloud.payload=JSON.stringify({...JSON.parse(cloud.payload),coins:9000});cloud.digest=await LittleLeafAuthorityCodec.hash(LittleLeafAuthorityCodec.fingerprint(cloud));await LittleLeafAuthorityCodec.verifyRecord(cloud);write('cloud',{schema:1,profileId:cloud.profileId,revision:cloud.revision,digest:cloud.digest,record:JSON.stringify(cloud)});return clone(cloud);}};
`;
let boot=fs.readFileSync(path.join(repo,'platform/web/little_leaf_firebase_boot.mjs'),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export async function start','async function start');
const injection=scripts.map(n=>'<script src="'+n+'"></script>').join('')+'<script>'+setup+boot+';window.__littleLeafFirebaseReady=start({projectId:"synthetic",authDomain:location.hostname},{localBinding:true});</script>';
let html=fs.readFileSync(path.join(web,'index.html'),'utf8').replace('window.__littleLeafVault.boot()','window.__littleLeafFirebaseReady.then(()=>window.__littleLeafVault.boot())').replace('<script src="index.js"></script>',injection+'<script src="index.js"></script>');
assert(html.includes(injection));
(async()=>{
 const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]).replace(/^\//,'')||'index.html';if(name.includes('..')){res.writeHead(403).end();return;}const file=scripts.includes(name)?path.join(repo,'platform/web',name):path.join(web,name);res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');res.setHeader('Content-Type',name.endsWith('.html')?'text/html':name.endsWith('.wasm')?'application/wasm':name.endsWith('.js')?'text/javascript':'application/octet-stream');if(name==='index.html')res.end(html);else if(fs.existsSync(file))fs.createReadStream(file).pipe(res);else res.writeHead(404).end();});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser,activePage;const observations=[],errors=[];
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--mute-audio'],timeout:20000,chromiumSandbox:true});const context=await browser.newContext({viewport:{width:1360,height:880}}),page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||/SCRIPT ERROR|Parse Error/.test(m.text()))errors.push(m.text());});
  activePage=page;
  async function state(action='state'){return page.evaluate(action=>{window.__bindingProbe(action);return JSON.parse(window.__bindingState);},action);}
  async function localEntry(){await page.getByRole('button',{name:'Play on this device',exact:true}).click();await page.waitForFunction(()=>typeof __bindingProbe==='function',{},{timeout:60000});await page.waitForFunction(()=>{__bindingProbe(['state']);return JSON.parse(__bindingState).ready;},{},{timeout:60000});}
  async function bind(){await state('settings');await page.waitForTimeout(150);const s=await state();observations.push({phase:'before native button click',state:s});console.log('Click native bind',s);await page.mouse.click(s.button.x,s.button.y);try{await page.getByRole('button',{name:'Sign in with Google',exact:true}).waitFor();}catch(e){observations.push({phase:'native bind blocked',state:await state()});await page.screenshot({path:path.join(evidence,'failure-native.png')});throw e;}const held=await state();assert(held.paused&&held.guiHeld&&held.bindingActive&&held.bindingFrozen);assert(!held.pending);return held;}
  await page.goto('http://127.0.0.1:'+server.address().port);await localEntry();await state('fixture');await page.waitForFunction(()=>{__bindingProbe(['state']);const s=JSON.parse(__bindingState);return s.revision>0&&!s.pending;});
  let original=await page.evaluate(()=>LittleLeafLocalGoogleEntry.readLocalRecord());const previousCloud=await page.evaluate(()=>__bindingQA.seedCloud());
  const held=await bind();observations.push({phase:'native freeze after terminal cancellation',state:held});await page.getByRole('button',{name:/Cancel.*return to local play/}).click();const restored=await state();assert(!restored.bindingActive&&!restored.guiHeld&&!restored.paused);assert.equal(await page.evaluate(()=>__bindingQA.read('writes')),null);assert.deepEqual(await page.evaluate(()=>__bindingQA.read('cloud').record),JSON.stringify(previousCloud));
  await state('pause');assert((await state()).paused,'Pause the synthetic restaurant before unchanged-state retry checks');
  await bind();await page.getByRole('button',{name:'Sign in with Google',exact:true}).click();await page.getByRole('button',{name:'Keep this device restaurant',exact:true}).waitFor();await page.screenshot({path:path.join(evidence,'native-web-explicit-choice.png')});
  original=await page.evaluate(()=>LittleLeafLocalGoogleEntry.readLocalRecord());assert.equal(JSON.parse(original.payload).coins,1200);
  await page.evaluate(()=>__bindingQA.write('interrupt',true));await page.getByRole('button',{name:'Keep this device restaurant',exact:true}).click();await page.getByRole('button',{name:'Play on this device',exact:true}).waitFor();assert.equal(await page.evaluate(()=>__bindingQA.read('writes')),1);await localEntry();
  await state('pause');assert((await state()).paused);
  await bind();await page.getByRole('button',{name:'Sign in with Google',exact:true}).click();
  // A reloaded native snapshot has a new local revision: require a fresh choice,
  // while the interrupted operation and its exact cloud result remain protected.
  await page.getByRole('button',{name:'Keep Google cloud restaurant',exact:true}).waitFor();assert.equal(await page.evaluate(()=>__bindingQA.read('writes')),1);
  const interrupted=await page.evaluate(async()=>{const journal=await LittleLeafFirebase.openJournal(indexedDB);return journal.read(['google-binding-v1','synthetic-google']);});assert.equal(interrupted.source.payload,original.payload);assert.equal(interrupted.previousCloud.record.payload,previousCloud.payload);
  await page.getByRole('button',{name:'Keep Google cloud restaurant',exact:true}).click();await page.getByRole('button',{name:'Continue with Google',exact:true}).waitFor();const cloud=await page.evaluate(()=>__bindingQA.read('cloud'));assert.equal(JSON.parse(cloud.record).payload,original.payload);assert.equal(await page.evaluate(()=>__bindingQA.read('writes')),2);
  const history=await page.evaluate(async()=>{const journal=await LittleLeafFirebase.openJournal(indexedDB);return journal.read(['google-binding-history-v1','synthetic-google']);});assert.equal(history[0].source.payload,original.payload);assert.equal(history[0].previousCloud.record.payload,previousCloud.payload);
  await page.getByRole('button',{name:'Return to local play',exact:true}).click();await bind();await page.getByRole('button',{name:'Sign in with Google',exact:true}).click();await page.getByRole('button',{name:'Verify existing binding',exact:true}).click();await page.getByRole('button',{name:'Continue with Google',exact:true}).waitFor();assert.equal(await page.evaluate(()=>__bindingQA.read('writes')),2);
  await page.getByRole('button',{name:'Continue with Google',exact:true}).click();await page.waitForFunction(()=>typeof __bindingProbe==='function'&&typeof LittleLeafLocalBinding==='undefined',{},{timeout:60000});await page.waitForFunction(()=>{__bindingProbe('state');return JSON.parse(__bindingState).ready;},{},{timeout:60000});const continued=await state();assert.equal(continued.profileId,cloud.profileId);assert.equal(continued.revision,cloud.revision);assert.equal(continued.coins,JSON.parse(original.payload).coins);observations.push({phase:'verified cloud continuation',state:continued});assert.equal(await page.evaluate(()=>__bindingQA.read('writes')),2);
  await page.screenshot({path:path.join(evidence,'native-web-cloud-continuation.png')});
  assert(!errors.some(x=>/SCRIPT ERROR|Parse Error|TypeError|ReferenceError/.test(x)),errors.join('\n'));
  fs.writeFileSync(path.join(evidence,'browser-receipt.json'),JSON.stringify({scope:'actual Godot Web native input/save/binding/reload, synthetic Auth/session/cloud boundary; no hosted Google acceptance',checks:['native terminal-before-save freeze','cancel restores local input without cloud write','explicit full-state comparison','interrupted post-CAS navigation preserves both records','persisted retry one write','repeated binding no duplicate write','verified cloud continuation native profile/revision/coins'],observations,errors,original,previousCloud,selected:cloud,exportReceipt:JSON.parse(fs.readFileSync(path.join(out,'export-receipt.json'),'utf8')),production_save_access:false},null,2));console.log('Actual native Web binding handshake passed.');await context.close();
 }catch(error){const dom=activePage?await activePage.locator('body').innerText().catch(()=> 'unavailable'):'';const buttons=activePage?await activePage.getByRole('button').allTextContents().catch(()=>[]):[];const trace=activePage?await activePage.evaluate(()=>window.__bindingTrace).catch(()=>[]):[];if(activePage)await activePage.screenshot({path:path.join(evidence,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(evidence,'browser-failure.json'),JSON.stringify({error:error.stack,observations,errors,dom,buttons,trace},null,2));console.log('Binding result trace',trace);throw error;}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exitCode=1;});
